import { type NextPage } from 'next';
import { Nunito } from 'next/font/google';
import Head from 'next/head';
import { Navbar } from '@/components/navbar';
import { LoginModal, RegisterModal, RentModal } from '@/components/modals';
import { ToasterProvider } from '@/providers';
import { Main, ClientOnly } from '@/components';

const font = Nunito({
  subsets: ['latin'],
});

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Airbnb Clone</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          <RentModal />
          <LoginModal />
          <RegisterModal />
          <Navbar />
          <Main />
        </ClientOnly>
      </main>
    </>
  );
};

export default Home;
