import { type NextPage } from 'next';
import { Nunito } from 'next/font/google';
import Head from 'next/head';
import { useSession } from 'next-auth/react';
import { Navbar } from '@/components/navbar';
import { LoginModal, RegisterModal } from '@/components/modals';
import ClientOnly from '@/components/ClientOnly';
import { ToasterProvider } from '@/providers';

const font = Nunito({
  subsets: ['latin'],
});

const Home: NextPage = () => {
  const { data: currentUser } = useSession();

  return (
    <>
      <Head>
        <title>Airbnb Clone</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          <LoginModal />
          <RegisterModal />
          <Navbar currentUser={currentUser}/>
        </ClientOnly>
      </main>
    </>
  );
};

export default Home;
